apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    specs:
      containers:
        - name: posts
          image: posts-service/posts:0.0.1